version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mommytalks
      - POSTGRES_PASSWORD=mommytalks
      - POSTGRES_DB=mommytalks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mommytalks"]
      interval: 10s
      timeout: 5s
      retries: 25

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mommytalks
      - DB_USER=mommytalks
      - DB_PASS=mommytalks
      - PORT=8080
      - HOST=0.0.0.0
      - PASSWORD=password
      - NODE_ENV=development
      - FIREBASE_TYPE=service_account
      - FIREBASE_PROJECT_ID=mommy-talks-388603
      - FIREBASE_PRIVATE_KEY_ID=9e900a4471488b6ac7a8b24765d64b0916bfe851
      - FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDK9mtGVXBqZ6qn\noSfS4BqV/qYcUN0iqe0xwxOPjS4DCCLRX/RJxHWOBi53R/jtShLG7S+q+OYEoojQ\nwbnxY6S4Gu16pTecHYJ73AMOXpnlU7rkCmMQDdAMxYtWXL6NGsK/cEMXfxmGyUkZ\n7gUqhgmqumus9RijzFMnECb9xCyrAQfbVq5h5gZKQglhDEA/AzFDGeuhDpidfwTy\nVHtID0hbSpBGJsm41HVAQge78yzEBdSfWKqY9sU8hqzMl8m+eYRWFVTOM7ws0sVK\n2Wr+Cq1U6gjoVpa0x3sHVdkITt0qh55MFHVrt03jEtOVRsDSArxHt1gAtyUpMDj7\ncTnhxKqdAgMBAAECggEATdoQ0wVB3ibOoIciAfLhb8iiifkAoePBbpWP4r/6NsJ/\nrIVcbJFVsDkxyKJMWyTPKAvh/XiErqFzznOI8g1RKSd3EVTfjFwLaZw+ddwWtw8T\ngJZ1YjqSI9wAcwuXMgPiUNFsgs5Hidqa1j3lMGcCvUDNvaW0IlxlRvYcprmBksPe\nkVgfxb+GhfLsh4Cxr3/7ovSNRRz5Yxsq3Xm16FGgJ8cqZuM0E2cLJWNtM+Bnluzo\n/+5E/gcUojqDmwVgeJ6mrfx7JgTlB7qsGL7qe0vQus8cDYo5nyujkDkIU6+FWzI6\nQlBxe+WDlUzb1Z+rttNZPKp/rkisEGDNMM0WBeCSFwKBgQD1+vbdj7xCjARHgF5F\nkaF56RrvsqyShY385Y/8UQkMqIGWDxz9vPT60r4nirePVfAFl2NStUxXHXpMhZoK\n/dADo0MO4UYFDI9Fi0JIjz60a0gz4dIlWTqOhs9ZIuaJviYDG0Y1XPht9onJbay6\n1ql/P5N+0GJSFzisaxUJmlc6nwKBgQDTOt+zMCJbv6b20qZCFSP4xYHdxqJG8Rcx\n2NCzwZ8Nq2isrTkHVS06uZ8UjFGfPUUrERxU+pfk9zQdNoT5FtrO/6pBYOdkDVxi\nZnAk83nD3Cfj5aWicYypafz29ydqUFhTB4OnBoMfa6W7BKwCXJIT0uM+zDaDvVPX\nmcBsG6HNQwKBgQCokI4B8VESzX7VPOvdgtoEgDD8WBYY5rsRtoNAZovsB8GeAsdc\nPtQm2qqC0HXQHRU5z6+56xHglQvNSrTwmVSmWYhHtyrTpPK9tpv6u2c+HlLBcxwe\nihItv8ZyEA+qDwtfj55CTW7VdGCiD62R8C8BS6EZA1aNaOpmhY9KIGFsgwKBgQCP\n0qNkL58FV45Iuw9HKXvPtDODnO77XMbNQvJ/opM4zIA+KsgMzRs5xA+j/xLIWQCS\nnVjsJ6Bq30LVrTyHGd+sV/pF/8QtpMdFnLg5AKrlCC8FBmVsIOKEq8z5HznwMnqh\nNhmXDWEUcMhseXbhOMShyNK//G4V70B6KY8STRIzXwKBgQDSJCNKBQTjoKBlwxIl\nnq5GFBmDf+g6FNx32m64FjrIsrmp2+uLBin3YFj1CmMlVH2mFBhRZPVHee/MOlOz\ngKMiEO13i0SH84XKU8CHztey9fK3Z0Z93MwQlmVQu6pEPNXZ5OKHKfb1wuJraAO4\nR4czAjFIXJ6WpI8UY+b4CKuAmQ==\n-----END PRIVATE KEY-----\n
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-c300a@mommy-talks-388603.iam.gserviceaccount.com
      - FIREBASE_CLIENT_ID=114769550586891155953
      - FIREBASE_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - FIREBASE_TOKEN_URI=https://oauth2.googleapis.com/token
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - FIREBASE_CLIENT_X509_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-c300a%40mommy-talks-388603.iam.gserviceaccount.com

    depends_on:
      postgres:
        condition: service_healthy
  
  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_HOST=backend
      - VITE_PORT = 8080
      - VITE_COMMENTS_PORT = 8000
      - VITE_FIREBASE_WEB_KEY = AIzaSyD-CGZkfkyQkYK-QSjnzF_BiYYPfs62RuQ
      - VITE_FIREBASE_PROJECT_ID = mommy-talks-388603
      - VITE_CLIENT_EMAIL = firebase-adminsdk-c300a@mommy-talks-388603.iam.gserviceaccount.com
      - VITE_AUTH_DOMAIN = mommy-talks-388603.firebaseapp.com
      - VITE_FIREBASE_STORAGE_BUCKET = mommy-talks-388603.appspot.com
      - VITE_FIREBASE_MESSAGING_SENDER_ID = 865112757769
      - VITE_FIREBASE_APP_ID = 1:865112757769:web:1d1c5815efdc2be0b08ad8
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:80/ || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 3

  comments:
    container_name: comments-service
    build: ./comments
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mommytalks:mommytalks@postgres:5432/mommytalks
    depends_on:
      frontend:
        condition: service_healthy

volumes:
  db:
    driver: local

